name: Unit Tests

on: [push]

jobs:
  tests:  # this must match the name you use in the branch protection settings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Unit Test - sum
        run: npm test ./__tests__/sum.test.js
      - name: Unit Test - full suite
        run: npm test ./__tests__/unit.test.js
